config/routes.rb
Footprints::Application.routes.draw do
  #get 'users/sign_in' => 'sessions#oauth_signin', :as => :oauth_signin

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
resources :users
  get 'auth/google_oauth2/callback', to: 'users/omniauth_callbacks#google_oauth2', :as => :new_session
  delete 'sessions/destroy', :as => :sessions_destroy
  #get 'sessions/oauth_signin' => 'sessions#oauth_signin', :as => :oauth_signin
  get "applicants" => 'applicants#index'
  get "applicants/unassigned" => 'applicants#unassigned', as: 'unassigned_applicants'
  get "applicants/new" => 'applicants#new', as: 'new_applicant'
  post "applicants/new" => 'applicants#create'
  post "applicants/submit" => 'applicants#submit'
  get "applicants/:id/deny_application" => "applicants#deny_application", as: "deny_application"
  get "applicants/:id/assign_craftsman" => "applicants#assign_craftsman", as: "assign_craftsman"
  get "applicants/:id/hire" => 'applicants#hire', as: "hire_applicant"
  post "update_state/:id" => 'applicants#update_state', :as => 'update_state'
  post "make_decision/:id" => 'applicants#make_decision', :as => 'make_decision'
  get "applicants/:id", to: 'applicants#show', as: 'applicant'
  post "applicants/:id" => 'applicants#update'
  get "applicants/:id/edit",to: 'applicants#edit', as: 'edit_applicant'
  delete "applicants/:id" => 'applicants#destroy'
  get "applicants/:id/offer_letter" => 'applicants#offer_letter'
  get "applicants/:id/offer_letter_form" => 'applicants#offer_letter_form'
  get "applicants/:id/onboarding_letters" => 'applicants#onboarding_letters'
  post "applicants/:id/update_employment_dates" => 'applicants#update_employment_dates'
  patch "applicants/:id/unarchive" => 'applicants#unarchive', as: "unarchive_applicant"

 # get 'users/:id', to: 'users#show', as: 'user'
  #get 'users/:id/edit', to: 'users#edit', as: 'edit_user'
  #post 'users/:id', to: 'users#update'

  post "messages/create" => 'messages#create'

  post "notes/create" => "notes#create", as: 'notes'
  get "notes/:id/edit" => "notes#edit", as: 'note'
  patch "notes/update/:id" => "notes#update", as: 'note_update'

  get "analytics" => "analytics#index"
  get "profile" => "craftsmen#profile", as: 'profile'
  get "craftsmen/seeking" => "craftsmen#seeking", as: 'craftsmen'
  put "craftsman/update" => "craftsmen#update"

  get "search_suggestions" => 'search_suggestions#index'
  get "craftsman_suggestions" => 'search_suggestions#craftsman_suggestions'
  get "dashboard/confirm_applicant_assignment" => "dashboard#confirm_applicant_assignment", as: 'confirm_applicant_assignment'
  get "dashboard/decline_applicant_assignment" => "dashboard#decline_applicant_assignment", as: 'decline_applicant_assignment'
  post "dashboard/decline_all_applicants" => "dashboard#decline_all_applicants", as: 'decline_all_applicants'

  get "templates" => "dashboard#email_templates", as: "templates"

  get "admin" => "admin#index", as: "admin"

  get "salaries/edit" => "salaries#edit", as: "salaries"
  post "salaries/create_monthly" => "salaries#create_monthly"
  post "salaries/create_annual" => "salaries#create_annual"
  post "salaries/update" => "salaries#update"
  delete "salaries/:id" => "salaries#destroy", as: "destroy_salary"

  get "reporting" => "reporting#index", as: "reporting"
  
  get "apprentices" => "apprentices#index", as: "apprentices"
  get "apprentices/:id" => "apprentices#edit"
  put "apprentices/:id" => "apprentices#update"

  root :to => "dashboard#index"
end

app/controllers/craftsmen_controller.rb
require './lib/repository'
require './lib/craftsmen/craftsmen_interactor'
require './lib/craftsmen/craftsmen_presenter'
require './lib/craftsmen/skills'

class CraftsmenController < ApplicationController
  before_filter :normalize_status, :only => [:index]

  def profile
    @craftsman = current_user.craftsman
  end

  def seeking
    craftsmen_presenter = CraftsmenPresenter.new(Footprints::Repository.craftsman)
    @craftsmen_seeking_residents = craftsmen_presenter.seeking_resident_apprentice
    @craftsmen_seeking_students  = craftsmen_presenter.seeking_student_apprentice
  end

  def update
    @craftsman = current_user.craftsman
    interactor = CraftsmenInteractor.new(@craftsman)
    interactor.update(craftsman_params)

    redirect_to profile_path, :notice => "Successfully saved profile"
  rescue CraftsmenInteractor::InvalidData => e
    @craftsman.attributes = craftsman_params

    flash.now[:error] = [e.message]
    render :profile
  end

  private

  def normalize_status
    if params["craftsman"]
      params["craftsman"]["status"] = params["craftsman"]["status"].titleize
    end
  end

  def craftsman_params
    params.require(:craftsman).permit(:status, :has_apprentice, :seeking, :skill, :location, :unavailable_until)
  end
end

app/helpers/craftsmen_helper.rb
module CraftsmenHelper
end

app/views/craftsmen/profile.html.erb
<div class="container profile">
  <div class="row">
    <div class="column one-third">
      <h1><%= @craftsman.name %></h1>
      <h4><%= @craftsman.email %></h4>
    </div>

    <div class="column two-thirds">
      <%= form_for @craftsman, :url => craftsman_update_path, :method => "PUT" do |f| %>
        <ul class="profile-list">
          <li>
            <%= f.check_box :has_apprentice, :class => "inline-input"  %>
            <%= f.label :has_apprentice, "Currently have an apprentice", :class => "inline-input" %>
          </li>
          <li>
            <%= f.check_box :seeking, :class => "inline-input" %>
            <%= f.label :seeking, "Interested in mentoring an apprentice", :class => "inline-input"  %>
          </li>
          <li>
            <%= f.label :skill_level %>
            <% Skills.available_skills.each do |skill_level, skill_key| %>
              <div class="actions">
                <%= f.radio_button :skill, skill_key, :checked => @craftsman.is_seeking_for?(skill_key), :class => "inline-input" %>
                <%= f.label :skill, skill_level, :value => skill_key, :class => "inline-input" %>
              </div>
            <% end %>
          </li>
          <li>
            <%= f.label :location %>
            <%= f.select :location, ["Chicago", "London", "Los Angeles"], {}, :class => "dropdown", :style => "width: 140px" %>
          </li>
          <li>
            <%= f.label :unavailable_until, "Unavailable until:" %>
            <%= f.text_field :unavailable_until, :placeholder => "I'm Available", :style => "width: 140px" %>
          </li>
          <li>
            <%= f.submit "Save", :class => "button primary" %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/craftsmen/seeking.html.erb
<div class="container seeking">
  <h1>Interested In Mentoring An Apprentice</h1>
  <div class="row">
    <div class="column half">
      <h5>Resident</h5>
      <% @craftsmen_seeking_residents.each do |craftsman| %>
        <p><%= craftsman.name %> - <%= mail_to craftsman.email, craftsman.email %></p>
      <% end %>
    </div>

    <div class="column half">
      <h5>Student</h5>
        <% @craftsmen_seeking_students.each do |craftsman| %>
          <p><%= craftsman.name %> - <%= mail_to craftsman.email, craftsman.email %></p>
        <% end %>
    </div>
  </div>
</div>