config/routes.rb
Footprints::Application.routes.draw do
  #get 'users/sign_in' => 'sessions#oauth_signin', :as => :oauth_signin

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
resources :users
  get 'auth/google_oauth2/callback', to: 'users/omniauth_callbacks#google_oauth2', :as => :new_session
  delete 'sessions/destroy', :as => :sessions_destroy
  #get 'sessions/oauth_signin' => 'sessions#oauth_signin', :as => :oauth_signin
  get "applicants" => 'applicants#index'
  get "applicants/unassigned" => 'applicants#unassigned', as: 'unassigned_applicants'
  get "applicants/new" => 'applicants#new', as: 'new_applicant'
  post "applicants/new" => 'applicants#create'
  post "applicants/submit" => 'applicants#submit'
  get "applicants/:id/deny_application" => "applicants#deny_application", as: "deny_application"
  get "applicants/:id/assign_craftsman" => "applicants#assign_craftsman", as: "assign_craftsman"
  get "applicants/:id/hire" => 'applicants#hire', as: "hire_applicant"
  post "update_state/:id" => 'applicants#update_state', :as => 'update_state'
  post "make_decision/:id" => 'applicants#make_decision', :as => 'make_decision'
  get "applicants/:id", to: 'applicants#show', as: 'applicant'
  post "applicants/:id" => 'applicants#update'
  get "applicants/:id/edit",to: 'applicants#edit', as: 'edit_applicant'
  delete "applicants/:id" => 'applicants#destroy'
  get "applicants/:id/offer_letter" => 'applicants#offer_letter'
  get "applicants/:id/offer_letter_form" => 'applicants#offer_letter_form'
  get "applicants/:id/onboarding_letters" => 'applicants#onboarding_letters'
  post "applicants/:id/update_employment_dates" => 'applicants#update_employment_dates'
  patch "applicants/:id/unarchive" => 'applicants#unarchive', as: "unarchive_applicant"

 # get 'users/:id', to: 'users#show', as: 'user'
  #get 'users/:id/edit', to: 'users#edit', as: 'edit_user'
  #post 'users/:id', to: 'users#update'

  post "messages/create" => 'messages#create'

  post "notes/create" => "notes#create", as: 'notes'
  get "notes/:id/edit" => "notes#edit", as: 'note'
  patch "notes/update/:id" => "notes#update", as: 'note_update'

  get "analytics" => "analytics#index"
  get "profile" => "craftsmen#profile", as: 'profile'
  get "craftsmen/seeking" => "craftsmen#seeking", as: 'craftsmen'
  put "craftsman/update" => "craftsmen#update"

  get "search_suggestions" => 'search_suggestions#index'
  get "craftsman_suggestions" => 'search_suggestions#craftsman_suggestions'
  get "dashboard/confirm_applicant_assignment" => "dashboard#confirm_applicant_assignment", as: 'confirm_applicant_assignment'
  get "dashboard/decline_applicant_assignment" => "dashboard#decline_applicant_assignment", as: 'decline_applicant_assignment'
  post "dashboard/decline_all_applicants" => "dashboard#decline_all_applicants", as: 'decline_all_applicants'

  get "templates" => "dashboard#email_templates", as: "templates"

  get "admin" => "admin#index", as: "admin"

  get "salaries/edit" => "salaries#edit", as: "salaries"
  post "salaries/create_monthly" => "salaries#create_monthly"
  post "salaries/create_annual" => "salaries#create_annual"
  post "salaries/update" => "salaries#update"
  delete "salaries/:id" => "salaries#destroy", as: "destroy_salary"

  get "reporting" => "reporting#index", as: "reporting"
  
  get "apprentices" => "apprentices#index", as: "apprentices"
  get "apprentices/:id" => "apprentices#edit"
  put "apprentices/:id" => "apprentices#update"

  root :to => "dashboard#index"
end

app/controllers/applicants_controller.rb
require 'repository'
require 'applicants/applicant_index_presenter'
require 'applicants/applicant_presenter'
require 'applicants/applicant_profile_presenter'
require 'notes/notes_presenter'
require 'applicants/applicant_interactor'
require 'applicants/eighthlight_applicants_interactor'
require 'applicants/applicant_finder'
require 'applicant_dispatch/dispatcher'
require 'argon/applicant_offer_letter_generator'
require 'argon/offer_letter_post'
require 'applicants/generate_onboarding_letter'
require 'date'
require 'will_paginate/array'

class ApplicantsController < ApplicationController
  include ApplicantsHelper

  before_filter :require_admin, :only => [:destroy, :new, :create, :hire, :make_decision, :unassigned, :assign_craftsman]

  def index
    @applicants    = Footprints::ApplicantFinder.new.get_applicants(params).paginate(:page => params[:page], :per_page => 12)
    @presenter     = ApplicantIndexPresenter.new(@applicants)
  end

  def new
    @applicant = repo.applicant.new
  end

  def create
    @applicant = repo.applicant.new(applicant_params)
    @applicant.save!
    redirect_to(applicant_path(@applicant), :notice => "Successfully created #{@applicant.name}")
  rescue StandardError => e
    flash.now[:error] = [e.message]
    render :new
  end

  def show
    @applicant = repo.applicant.find(params[:id])
    @presenter = ApplicantProfilePresenter.new(@applicant)
    @notes     = NotesPresenter.new(@applicant.notes)
    @note      = Note.new({:applicant_id => @applicant.id})
  end

  def edit
    @applicant = repo.applicant.find(params[:id])
  end

  def update
    @applicant = repo.applicant.find(params[:id])
    interactor = ApplicantInteractor.new(@applicant, applicant_params_for_update, session[:id_token])
    interactor.update
    redirect_to applicant_path(@applicant), :notice => interactor.get_notice
  rescue StandardError => e
    if @applicant.errors.full_messages.empty?
      flash.now[:error] = [e.message]
    else
      flash.now[:error] = @applicant.errors.full_messages
    end
    render :edit
  end

  def unarchive
    applicant = repo.applicant.find(params[:id])
    applicant.update_attributes!(archived: false)
    redirect_to applicants_path
  end

  def update_state
    @applicant = repo.applicant.find(params[:id])
    ApplicantInteractor.new(@applicant, applicant_params).update_state
    render :json => { :success => "true" }
  rescue StandardError => e
    render :json => { :success => "false", :message => e.message }
  end

  def deny_application
    @applicant = repo.applicant.find(params[:id])
    @applicant.update_attributes({:hired => "no", :archived => true})
    path_for_redirect = determine_redirect_path_for_denial(@applicant)
    redirect_to path_for_redirect, :notice => "Successfully denied and archived applicant"
  end

  def update_employment_dates
    @applicant = repo.applicant.find(params[:id])
    end_date = calculate_end_date(params[:applicant][:start_date], params[:applicant][:duration])
    params[:applicant][:end_date] = end_date
    ApplicantInteractor.new(@applicant, employment_date_params).update
    render :json => { :success => "true",
                      :applicantId => @applicant.id,
                      :duration => params[:applicant][:duration],
                      :pt_ft => params[:applicant][:pt_ft],
                      :hours_per_week => params[:applicant][:hours_per_week],
                      :withdraw_offer_date => params[:applicant][:withdraw_offer_date] }
  rescue StandardError => e
    render :json => { :sucesss => "false", :message => e.message }
  end

  def hire
    @applicant = repo.applicant.find(params[:id])
    @presenter = ApplicantProfilePresenter.new(@applicant)
    render :layout => false
  end

  def make_decision
    applicant = repo.applicant.find(params[:id])
    ApplicantInteractor.new(applicant, hiring_decision_params, session[:id_token]).update_applicant_for_hiring
    redirect_to applicant_path(applicant), :flash => { :notice => "Applicant hired" }
  rescue StandardError => e
    flash[:error] = [e.message]
    redirect_to applicant_path(applicant)
  end

  def destroy
    repo.applicant.destroy(params[:id])
    redirect_to(applicants_path, notice: "Successfully deleted applicant")
  end

  def submit
    status, body = EighthlightApplicantsInteractor.apply(eighthlight_applicant_params)
    render :status => status, :text => body, :layout => false
  end

  def unassigned
    @applicant_presenter = ApplicantPresenter.new
    applicants = repo.applicant.get_unassigned_unarchived_applicants
    @applicants = @applicant_presenter.sort_by_date(applicants)
  end

  def assign_craftsman
    applicant = repo.applicant.find_by_id(params[:id])
    steward = repo.craftsman.find_by_email(ENV['STEWARD'])
    ApplicantDispatch::Dispatcher.new(applicant, steward).assign_applicant
    redirect_to(unassigned_applicants_path, notice: "Assigned #{applicant.name} to #{applicant.assigned_craftsman}")
  end

  def offer_letter_form
    applicant = repo.applicant.find(params[:id])
    @duration_options = repo.monthly_apprentice_salary.find_all_durations_by_location(applicant.location)
    render_offer_letter_form(applicant.location)
  end

  def offer_letter
    applicant = repo.applicant.find(params[:id])
    generator = ApplicantOfferLetterGenerator.new(applicant, params)
    json_data = generator.build_offer_letter_as_json
    NotificationMailer.offer_letter_generated(applicant).deliver
    respond_to do |format|
      format.pdf { send_data OfferLetterPost.get_pdf(json_data), :type => "application/pdf" }
    end
  end

  def onboarding_letters
    applicant = repo.applicant.find(params[:id])
    template_root = "#{Rails.root}/lib/argon"
    onboarding_letter = GenerateOnboardingLetter.new(applicant, template_root).call
    respond_to do |format|
      format.pdf { send_data(onboarding_letter, :type => "application/pdf") }
    end
  end

  private

  def render_offer_letter_form(location)
    if location_is_unknown(location)
      render "unknown_location_offer_letter_form", layout: false
    elsif same_location?(location, "london")
      render "london_offer_letter_form", layout: false
    elsif same_location?(location, "chicago")
      render "chicago_offer_letter_form", layout: false
    elsif same_location?(location, "los angeles")
      render "los_angeles_offer_letter_form", layout: false
    end
  end

  def location_is_unknown(location)
    location.to_s == ''
  end

  def same_location?(location_one, location_two)
    location_one.downcase == location_two.downcase
  end

  def eighthlight_applicant_params
    {
      :name              => params[:name],
      :applied_on        => Time.zone.now.to_date,
      :email             => params[:email],
      :url               => params[:publication],
      :about             => params[:story],
      :software_interest => params[:passion],
      :reason            => params[:desire],
      :discipline        => params[:type],
      :location          => params[:location],
      :skill             => params[:position]
    }
  end

  def calculate_end_date(start_date, duration)
    target_day_of_week = 7
    start = Date.parse(start_date)
    end_date = start >> duration.to_i
    distance = target_day_of_week - end_date.cwday
    end_date + (distance.abs < 4 ? distance : distance.abs - 7).days
  end

  def employment_date_params
    params.require(:applicant).permit(:start_date, :end_date, :offered_on)
  end

  def hiring_decision_params
    params.require(:applicant).permit(:decision_made_on, :hired, :mentor)
  end

  def applicant_params
    params.require(:applicant).permit(:name, :email, :applied_on, :initial_reply_on, :sent_challenge_on, :completed_challenge_on, :reviewed_on, :resubmitted_challenge_on, :decision_made_on, :assigned_craftsman, :code_submission, :codeschool, :college_degree, :cs_degree, :worked_as_dev, :additional_notes, :url, :craftsman_id, :has_steward, :skill, :discipline, :archived, :hired, :about, :software_interest, :reason, :start_date, :end_date, :location, :offered_on)
  end

  def applicant_params_for_update
    params.require(:applicant).permit(:name, :email, :initial_reply_on, :sent_challenge_on, :completed_challenge_on, :reviewed_on, :resubmitted_challenge_on, :decision_made_on, :assigned_craftsman, :code_submission, :codeschool, :college_degree, :cs_degree, :worked_as_dev, :additional_notes, :url, :craftsman_id, :has_steward, :skill, :discipline, :archived, :hired, :about, :software_interest, :reason, :start_date, :end_date, :location, :offered_on)
  end

  def determine_redirect_path_for_denial(applicant)
    if applicant.assigned_craftsman
      root_path
    else
      unassigned_applicants_path
    end
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
  def format_label(field)
    field.to_s.titleize
  end

  def days_since_last_action(applicant)
    state = ApplicantStateMachine.determine_state(applicant)
    current_state_date = applicant.send(state)
    return "No Data Available" if current_state_date.nil?
    return (Date.today - current_state_date).to_i
  end

  def display_end_date(date)
    date ? format_date(date) : "N/A"
  end

  def format_date(date)
    date.strftime(month_day_year)
  end

  def display_date(date)
    date.strftime(month_day_year)
  end

  def month_day_year
    "%b %-d, %Y"
  end
end

app/views/applicants/_applicant_actions.html.erb
<div class="applicant-actions" data-applicant-id='<%= app.id %>'>
  <% if presenter.can_be_unarchived? %>
    <%= form_for app, :url => unarchive_applicant_path(app), :method => :patch do |f| %>
      <%= f.hidden_field :archived, :value => true %>
      <%= f.submit "Unarchive", :class => "button primary unarchive" %>
    <% end %>
  <% end %>
  <%= raw(presenter.hire_action) if admin? %>
  <% if presenter.can_be_denied? %>
  <%= link_to "Deny", deny_application_path(app), :class => "button secondary", data: {confirm: "Are you sure you want to deny this applicant? This action will archive all information about this applicant, but discontinue his/her progress through the application process."} %>
  <% end %>
</div>

app/views/applicants/_applicant_basic_info.html.erb
<% unless @presenter.url.empty? %>
  <p><span class="applicant-label">URL</span>:
  <% @presenter.url.each do |link| %>
    <%= link_to link, link, :target => "_blank" %>
  <% end %>
  </p>
<% end %>

<% if @applicant.code_submission.nil? %>
  <%= "" %>
<% else %>
  <h2>Code Submission</h2>
  <p><%= link_to @applicant.code_submission, @applicant.code_submission, :target => "_blank" %></p>
<% end %>

app/views/applicants/_applicant_card.html.erb
<!-- Applicant Profile Card -->

<div class="applicant-profile applicant-data">

  <div class="card-header">
    <div class="actions">
      <%= link_to "Edit", controller: "applicants", action: "edit", id: app %>
      <span class="divider"> &middot; </span>
      <%= link_to "Delete", applicant_path(app), method: :delete, data: {confirm: "Are you sure you want to delete this applicant profile? This action will permanently delete all data associated with this applicant."} if admin? %>
    </div>

    <%= link_to app.name, applicant_path(app), :class => "applicant-name" %>

    <div class="actions">
      <%= mail_to app.email, "Email" %>
      <span class="divider"> &middot; </span>
      <span class="card-sub-header">Applied <%= display_date(app.applied_on) %></span>
      <span class="divider"> &middot; </span>
      <span class="card-sub-header">
        <% if app.assigned_craftsman %>
          Assigned to <%= app.assigned_craftsman %>
        <% else %>
          Needs Craftsman
        <% end %>
      </span>
    </div>

    <ul class="card-data-list applicant-data">
      <li>
      <span class="card-data"><%= presenter.skill(app) %></span>
      <span class="card-label">Level</span>
      </li>
      <li>
        <span class="card-data"><%= presenter.discipline(app) %></span>
        <span class="card-label">Discipline</span>
      </li>
      <li>
        <span class="card-data"><%= presenter.location(app) %></span>
        <span class="card-label">Location</span>
      </li>
      <li>
        <span class="card-data"><%= presenter.current_state(app) %></span>
        <span class="card-label">Status</span>
      </li>
      <li>
        <% if days_since_last_action(app).is_a?(Integer) && days_since_last_action(app) > 7 %>
          <p class="card-data alert alert-warning"><%= days_since_last_action(app) %> days ago</p>
        <% else %>
          <p class="card-data alert"><%= days_since_last_action(app) %> days ago</p>
        <% end %>
      <span class="card-label">Contacted</span>
      </li>
    </ul>

    <h5>Process Timeline</h5>
    <div class="status card" data-applicant-id="<%= @applicant.id %>">
      <div class="state-holder">
        <span class="applied_on state tooltip <%= presenter.tooltip_state(app, "applied_on") %>"><strong>Applied</strong></span>
        <span class="initial_reply_on state tooltip <%= presenter.tooltip_state(app, "initial_reply_on") %>"><strong>Contacted</strong></span>
        <span class="sent_challenge_on state tooltip <%= presenter.tooltip_state(app, "sent_challenge_on") %>"><strong>Requested Submission</strong></span>
        <span class="completed_challenge_on state tooltip <%= presenter.tooltip_state(app, "completed_challenge_on") %>"><strong>Submitted Code</strong></span>
        <span class="reviewed_on state tooltip <%= presenter.tooltip_state(app, "reviewed_on") %>"><strong>Completed Review</strong></span>
        <span class="offered_on state tooltip <%= presenter.tooltip_state(app, "offered_on") %>"><strong><%= presenter.offer_text %></strong></span>
      </div>
    </div>

    <p class="status-text">
      <i class="status-icon fa fa-<%= presenter.waiting_state_class(app) %>"></i>
      <span><%= presenter.waiting_state(app) %></span>
    </p>
  </div>
</div>

app/views/applicants/_applicant_interactions.html.erb
<div class="applicant-interactions">
  <h2>Interactions</h2>
  <% if @presenter.interactions == {} %>
    <p>No Interactions Yet</p>
  <% else %>
    <% @presenter.interactions.each_pair do |label, date| %>
      <p><span class="applicant-label"><%= label %></label>: <%= date %></p>
    <% end %>
  <% end %>
</div>

app/views/applicants/_applicant_masterdata_form.html.erb
<div class='form-whole-width'>
  <%= form.label :name, 'Applicant Name' %>
  <%= form.text_field :name, id: 'applicant-name' %>

  <%= form.label :applied_on, 'Applied On' %>
  <%= form.text_field :applied_on, id: 'applied_on', disabled: local_assigns.has_key?(:disable_applied_on) ? disable_applied_on : false %>
</div>

app/views/applicants/_applicant_question_form.html.erb
<div class='form-whole-width'>
  <%= form.label :location %>
  <p>
    <%= form.select :location, ["Chicago", "London", "Los Angeles"], {}, class: "dropdown", style:"width: 140px" %>
  </p>

  <%= form.label :discipline %>
  <p>
    <%= form.select :discipline, {"Developer" => "developer", "Designer" => "designer"}, {}, class: "dropdown", style: "width: 140px" %>
  </p>

  <%= form.label :skill %>
  <p>
    <%= form.select :skill, {"Craftsman" => "craftsman", "Resident" => "resident", "Student" => "student"}, {}, class: "dropdown", style: "width: 140px" %>
  </p>

  <%= form.label :about, 'Their Story' %>
  <p>
    <%= form.text_area :about, id: 'about_applicant' %>
  </p>

  <%= form.label :software_interest, 'Why They Love Creating Software:' %>
  <p>
    <%= form.text_area :software_interest, id: 'applicant_software_interest' %>
  </p>

  <%= form.label :reason, 'Why They Want To Be An Apprentice:' %>
  <p>
    <%= form.text_area :reason, id: 'applicant_reason' %>
  </p>
</div>

app/views/applicants/_applicant_questions.html.erb
<% if @presenter.has_application_questions? %>
  <% if @applicant.about != nil %>
    <h2>What's your story?</h2>
    <p><%= @applicant.about.gsub(/\n/, '<br/>').delete("\\").delete("---").html_safe %></p>
  <% end %>

  <% if @applicant.software_interest != nil %>
    <h2>Why do you love creating software?</h2>
    <p><%= @applicant.software_interest.gsub(/\n/, '<br/>').delete("\\").delete("---").html_safe  %></p>
  <% end %>

  <% if @applicant.reason != nil %>
    <h2>Why do you want to be an apprentice?</h2>
    <p><%= @applicant.reason.gsub(/\n/, '<br/>').delete("\\").delete("---").html_safe %></p>
  <% end %>

<% else %>
  <div class="heading row">
    <h2>No Answers to Application Questions</h2>
  </div>
<% end %>

app/views/applicants/_note_form.html.erb
<%= form_for @note do |f| %>
  <%= f.text_area :body, :placeholder => "Leave a note about this applicant...", :class => "applicant-note-form-text-area" %>
  <%= f.hidden_field :applicant_id, :value => @note.applicant_id %>
  <%= f.submit "Submit", :class => "button primary" %>
<% end %>

app/views/applicants/_notes.html.erb
<h5>Notes</h5>
<% @notes.each do |note| %>
  <div class="note">
    <div class="note-header">
      <p class="note-author"><%= note.craftsman %> · <%= note.updated_at %><p>
      <% if note.created_by?(@current_user) %>
        <%= link_to "Edit", note_path(note.id), :class => 'edit-note button small secondary' %>
      <% end %>
    </div>
    <div class="note-body">
      <%= note.body %>
    </div>
  </div>
<% end %>

app/views/applicants/chicago_offer_letter_form.html.erb
<div id='offer-letter-form'>
  <div id='dialog-form' title='Generate Offer Letter' autofocus>
    <div id='modal-errors'></div>
    <form id='employment-dates' class="form">
      <label for='applicant[:start_date]'>Start Date: </label>
      <input data-id='start_date' name='applicant[:start_date]' class='start_date' />
      <br>
      <label for='duration'>Duration (in months) </label>
      <select data-id='duration'>
        <% @duration_options.each do |duration| %>
          <option value="<%= duration %>"><%= duration %></option>
        <% end %>
      </select>
      <div id='admin_confirmation'>
        <p>Confirmed with admin</p>
        <input id='confirmed_with_admin' type='checkbox' value='confirmed_with_admin' name='confirmed_with_admin' />
        <label for='confirmed_with_admin'>I have confirmed with Paul Pagel that an offer letter can be extended to this applicant</label>
      </div>
    </form>
  </div>
</div>

app/views/applicants/edit.html.erb
<div class="container">
  <p><%= link_to "← Back to Profile", applicant_path(@applicant) %></p>
  <div class="heading row">
    <h1>Edit <%= @applicant.name %></h1>
  </div>

  <%= form_for :applicant, url: applicant_path(@applicant.id), method: :post, class: 'form' do |form| %>
    <%= render partial: "applicant_masterdata_form", locals: { form: form, disable_applied_on: true } %>
    <%= render partial: "applicant_question_form", locals: { form: form } %>
    <%= render partial: "applicant_form", locals: { form: form } %>
    <div class="row">
      <%= form.submit value: 'Update Profile', class: 'button primary' %>
    </div>
  <% end %>
</div>

app/views/applicants/hire.html.erb
<div id='confirm-hire'>
<%= form_for @applicant, url: make_decision_path(@applicant.id), method: :post, class: 'form' do |form| %>
  <h4>Clicking submit will post this applicant to warehouse with the information below. Please double check all information relating to this applicant before submitting.</h4>
  <%= form.label :mentor, 'Mentor' %>
  <p><%= form.text_field :mentor, id: 'mentor', class: 'ui-autocomplete-input', value: @applicant.assigned_craftsman %></p>
  <p>Start Date:  <%= @presenter.display_date(@applicant.start_date) %></p>
  <p>End Date:  <%= @presenter.display_date(@applicant.end_date) %></p>
<% end %>
</div>

app/views/applicants/index.html.erb
<div class="container applicants-list">
  <div class="actions">
    <%= form_tag applicants_path, method: :get do %>
      <%= text_field_tag 'term', params[:term], {:class => "form-narrow left", :placeholder => "Search Applicants by Name"} %>
    <% end %>

    <%= form_for :applicants, url: applicants_path, method: :get, html: {} do |f| %>
      <div class="form-narrow left margin-left">
      <%= select_tag(:status, options_for_select([['Filter By Current State'], ['All', 'all'], ['Needs Reply', 'applied_on'], ['Sent Initial Contact', 'initial_reply_on'], ['Challenge Sent', 'sent_challenge_on'], ['Needs Review', 'completed_challenge_on'], ['Needs Decision', 'reviewed_on'], ["Archived", "archived"]], selected: "Choose Filter", disabled: "Choose Filter"), { :class => "dropdown", :onchange => "this.form.submit();"}) %>
      </div>
    <% end %>

    <%= link_to 'Add Applicant', new_applicant_path, :class => "new-applicant-link button primary" if admin? %>
  </div>

  <% @applicants.each_slice(3) do |slice| %>
    <div class="row">
      <% slice.each do |app| %>
        <div class="column one-third">
          <%= render :partial => 'applicant_card_index', :locals => {:app => app, :presenter => @presenter} %>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>

  <div class="row">
    <section id="pagination">
    <%= will_paginate @applicants %>
    </section>
  </div>
</div>

app/views/applicants/los_angeles_offer_letter_form.html.erb
<div id='offer-letter-form'>
  <div id='dialog-form' title='Generate Offer Letter' autofocus>
    <div id='modal-errors'></div>
    <form id='employment-dates' class="form">
      <label for='applicant[:start_date]'>Start Date: </label>
      <input data-id='start_date' name='applicant[:start_date]' class='start_date' />
      <br>
      <label for='duration'>Duration (in months) </label>
      <select data-id='duration'>
        <% @duration_options.each do |duration| %>
          <option value="<%= duration %>"><%= duration %></option>
        <% end %>
      </select>
      <div id='admin_confirmation'>
        <p>Confirmed with admin</p>
        <input id='confirmed_with_admin' type='checkbox' value='confirmed_with_admin' name='confirmed_with_admin' />
        <label for='confirmed_with_admin'>I have confirmed with Clare Heyward that an offer letter can be extended to this applicant</label>
      </div>
    </form>
  </div>
</div>